export const BANCO_EXERCICIOS = [
  { nome: "Supino Reto", grupo: "Peitoral" },
  { nome: "Supino Inclinado", grupo: "Peitoral" },
  { nome: "Crucifixo", grupo: "Peitoral" },
  { nome: "Peck Deck", grupo: "Peitoral" },
  { nome: "Pulley Frente", grupo: "Costas" },
  { nome: "Remada Curvada", grupo: "Costas" },
  { nome: "Remada Unilateral", grupo: "Costas" },
  { nome: "Levantamento Terra", grupo: "Costas" },
  { nome: "Desenvolvimento", grupo: "Ombros" },
  { nome: "Elevação Lateral", grupo: "Ombros" },
  { nome: "Rosca Direta", grupo: "Bíceps" },
  { nome: "Rosca Alternada", grupo: "Bíceps" },
  { nome: "Tríceps Pulley", grupo: "Tríceps" },
  { nome: "Tríceps Francês", grupo: "Tríceps" },
  { nome: "Agachamento Livre", grupo: "Quadríceps" },
  { nome: "Leg Press 45", grupo: "Quadríceps" },
  { nome: "Cadeira Extensora", grupo: "Quadríceps" },
  { nome: "Mesa Flexora", grupo: "Isquiotibiais" },
  { nome: "Stiff", grupo: "Isquiotibiais" },
  { nome: "Panturrilha em Pé", grupo: "Panturrilha" },
  { nome: "Abdominais Crunch", grupo: "Core" },
  { nome: "Prancha", grupo: "Core" },
  { nome: "Abdominal Oblíquo", grupo: "Core" },
  { nome: "Glúteo no Cross", grupo: "Glúteo" },
  { nome: "Elevação Pélvica", grupo: "Glúteo" },
  { nome: "Corrida Esteira", grupo: "Cardio" },
  { nome: "Bike Ergométrica", grupo: "Cardio" },
  { nome: "Elíptico", grupo: "Cardio" },
  { nome: "Pular Corda", grupo: "Cardio" },
  { nome: "Burpee", grupo: "Full Body" },
] as const;

export type Exercicio = (typeof BANCO_EXERCICIOS)[number];
